/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Coding {
  code: string;
  codeDisplay: string | null;
  codeSystem: string;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<number>;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
  versionId: string;
}

export interface ProcessEvent {
  codingId: number;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  endDate: Timestamp | null;
  id: Generated<number>;
  isDatetime: Generated<boolean>;
  startDate: Timestamp;
  status: string | null;
  statusCode: string | null;
  statusDescription: string | null;
  systemRecordId: number;
  transactionId: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface RecordKind {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<number>;
  kind: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface RecordLinkage {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<number>;
  linkedSystemRecordId: number;
  systemRecordId: number;
  transactionId: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface System {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface SystemRecord {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<number>;
  recordId: string;
  recordKindId: number;
  systemId: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface Transaction {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface Version {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface DB {
  coding: Coding;
  processEvent: ProcessEvent;
  recordKind: RecordKind;
  recordLinkage: RecordLinkage;
  system: System;
  systemRecord: SystemRecord;
  transaction: Transaction;
  version: Version;
}
