/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PiesCoding {
  code: string;
  codeDisplay: string | null;
  codeSystem: string;
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  id: Generated<number>;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
  versionId: string;
}

export interface PiesProcessEvent {
  codingId: number;
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  endDate: Timestamp | null;
  id: Generated<number>;
  isDatetime: Generated<boolean>;
  startDate: Timestamp;
  status: string | null;
  statusCode: string | null;
  statusDescription: string | null;
  systemRecordId: number;
  transactionId: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface PiesRecordKind {
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  id: Generated<number>;
  kind: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface PiesRecordLinkage {
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  id: Generated<number>;
  linkedSystemRecordId: number;
  systemRecordId: number;
  transactionId: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface PiesSystem {
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  id: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface PiesSystemRecord {
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  id: Generated<number>;
  recordId: string;
  recordKindId: number;
  systemId: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface PiesTransaction {
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  id: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface PiesVersion {
  createdAt: Generated<Timestamp>;
  createdBy: Generated<string>;
  id: string;
  updatedAt: Timestamp | null;
  updatedBy: string | null;
}

export interface DB {
  'pies.coding': PiesCoding;
  'pies.processEvent': PiesProcessEvent;
  'pies.recordKind': PiesRecordKind;
  'pies.recordLinkage': PiesRecordLinkage;
  'pies.system': PiesSystem;
  'pies.systemRecord': PiesSystemRecord;
  'pies.transaction': PiesTransaction;
  'pies.version': PiesVersion;
}
