version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHOST: db
      PGDATABASE: peach
      PGUSER: app
      PGPASSWORD: postgres
    ports:
      - '3000:3000'
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
  db:
    image: docker.io/postgres:16-alpine
    environment:
      POSTGRES_DB: peach
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
