name: .Core Deployer

on:
  workflow_call:
    inputs:
      command:
        description: 'The terragrunt command to run'
        required: true
        type: string
        default: apply
      environment:
        description: 'The name of the environment to deploy to'
        required: true
        type: string
        default: dev
      tag:
        description: 'The tag of the containers to deploy'
        required: false
        type: string
        default: latest

env:
  AZURE_REGION: Canada Central
  TF_LOG: ERROR

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  infra:
    environment: ${{ inputs.environment }}
    name: Terraform ${{inputs.command}} ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Verify required GitHub secrets
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          VNET_RESOURCE_GROUP_NAME: ${{ secrets.VNET_RESOURCE_GROUP_NAME }}
          VNET_ADDRESS_SPACE: ${{ secrets.VNET_ADDRESS_SPACE }}
          VNET_NAME: ${{ secrets.VNET_NAME }}
        run: |
          missing=0
          for secret in AZURE_CLIENT_ID AZURE_TENANT_ID AZURE_SUBSCRIPTION_ID VNET_RESOURCE_GROUP_NAME VNET_ADDRESS_SPACE VNET_NAME; do
            if [ -z "${!secret}" ]; then
              echo "Missing required secret: $secret"
              missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then
            echo "One or more required secrets are missing. Failing workflow."
            exit 1
          fi
      - name: Azure CLI Login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - name: Terraform Init
        working-directory: infra/core
        run: |
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.VNET_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=tfstatenrpeach${{ inputs.environment }}" \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -backend-config="use_oidc=true"
      - name: Terraform ${{ inputs.command }}
        working-directory: infra/core
        env:
          TF_VAR_app_name: nr-peach
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_common_tags: >-
            {"app_name":"peach","environment":"${{ inputs.environment }}","instance":"core","repo_name":"nr-peach","managed_by":"terraform"}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_vnet_address_space: ${{ secrets.VNET_ADDRESS_SPACE }}
          TF_VAR_vnet_name: ${{ secrets.VNET_NAME }}
          TF_VAR_vnet_resource_group_name: ${{ secrets.VNET_RESOURCE_GROUP_NAME }}
        run: |
          args="-input=false"
          if [[ "${{ inputs.command }}" == "apply" || "${{ inputs.command }}" == "destroy" ]]; then
            args="$args -auto-approve"
          fi
          terraform ${{ inputs.command }} $args
