name: Push

env:
  ACRONYM: peach
  APP_NAME: nr-peach
  # NAMESPACE_PREFIX:

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build & Push
        uses: bcgov/action-builder-ghcr@ace71f7a527ca6fc43c15c7806314be5a4579d2c # v2.3.0
        with:
          package: ${{ env.APP_NAME }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          build_context: .
          token: ${{ secrets.GITHUB_TOKEN }}
