name: Push

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      # - name: Set up Cosign
      #   uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3.9.1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Container Metadata tags
        id: meta
        uses: docker/metadata-action@v5.7.0
        # env:
        #   DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ghcr.io/${{ github.repository }}
          # Creates tags based off of branch names and semver tags
          tags: |
            type=sha
            type=sha,prefix=,format=long
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and Push to Container Registry
        id: builder
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          # provenance: true
          # sbom: true
      # - name: Sign the images with GitHub OIDC Token
      #   env:
      #     DIGEST: ${{ steps.builder.outputs.digest }}
      #     TAGS: ${{ steps.meta.outputs.tags }}
      #   run: |
      #     images=""
      #     for tag in ${TAGS}; do
      #       images+="${tag}@${DIGEST} "
      #     done
      #     cosign sign --yes ${images}
      - name: Attest
        uses: actions/attest@v2.4.0
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.builder.outputs.digest }}
          predicate-type: 'https://in-toto.io/attestation/release/v0.1'
          predicate: '{"purl":"pkg:oci/${{ github.repository }}"}'
      # Non-buildx variant
      - name: Inspect image
        run: docker image inspect ghcr.io/${{ github.repository }}:latest
      # buildx variant
      # - name: Inspect image
      #   run: |
      #     docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ github.sha }} --format '{{json .}}' > manifest.json
      #     cat manifest.json
      # - name: List & Verify image attestations
      #   run: |
      #     cosign tree ghcr.io/${{ github.repository }}@${{ steps.builder.outputs.digest }}
      #     cosign verify ghcr.io/${{ github.repository }}@${{ steps.builder.outputs.digest }} \
      #       --certificate-identity-regexp 'https://github.com/${{ github.repository }}/.+/.+/.+@${{ github.ref }}' \
      #       --certificate-oidc-issuer https://token.actions.githubusercontent.com
