name: Push

on:
  push:
    branches:
      - '**'
    tags:
      - v*.*.*
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      attestations: write # for actions/attest-build-provenance attestation persistence
      contents: write # set to write for anchore/sbom-action artifact uploads during release builds
      id-token: write # for actions/attest-build-provenance OIDC token to request a Sigstore signing certificate
      packages: write # for docker/build-push-action to push images to GitHub Container Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build & Push
        uses: bcgov/action-builder-ghcr@v4.0.0
        with:
          package: ${{ env.APP_NAME }}
          build_context: .
          tags: |
            ${{ github.event.number }}
            ${{ github.sha }}
            latest
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}
