name: Push

on:
  push:
    branches:
      - '**'
    tags:
      - v*.*.*
  release:
    types:
      - published

jobs:
  build-push:
    name: Build & Push
    concurrency:
      group: build-push-${{ github.event.number || 'latest' }}
      cancel-in-progress: true
    uses: ./.github/workflows/.builder.yaml
    secrets: inherit
