name: Push

env:
  ACRONYM: peach
  APP_NAME: nr-peach

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      attestations: write
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build & Push
        uses: bcgov/action-builder-ghcr@v3.0.0
        with:
          package: ${{ env.APP_NAME }}
          build_context: .
          tags: |
            ${{ github.event.number }}
            ${{ github.sha }}
            latest
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}
