---
name: Tests

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test-app:
    name: Unit Tests
    runs-on: ubuntu-latest
    outputs:
      HAS_SONAR_SECRETS: ${{ steps.check-secrets.outputs.HAS_SONAR_SECRETS }}
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - '20.x'
          - '22.x'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Check SonarCloud Secrets
        id: check-secrets
        run: |
          echo "HAS_SONAR_SECRETS=${{ secrets.SONAR_TOKEN != '' }}" >> $GITHUB_OUTPUT
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v4.2.3
        id: cache-app
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-app-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-app-${{ env.cache-name }}-
            ${{ runner.os }}-app-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-app.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint
        if: "matrix.node-version == '22.x'"
        run: npm run lint
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: Save Coverage Results
        if: matrix.node-version == '22.x'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-app
          path: ${{ github.workspace }}/coverage
          retention-days: 1
      - name: Monitor Coverage
        if: "matrix.node-version == '22.x' && ! github.event.pull_request.head.repo.fork"
        uses: slavcodev/coverage-monitor-action@398c4cbbb710e549a8407fdef96ae8b9454d0463 # 1.10.0
        with:
          comment_mode: update
          comment_footer: false
          comment_context: Coverage Report
          coverage_path: coverage/clover.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold_alert: 50
          threshold_warning: 80

  test-coverage:
    name: Publish to SonarCloud
    needs: test-app
    if: needs.test-app.outputs.HAS_SONAR_SECRETS == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v4.2.3
        id: cache-app
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-app-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-app-${{ env.cache-name }}-
            ${{ runner.os }}-app-
            ${{ runner.os }}-
      - name: Restore Coverage Results
        uses: actions/download-artifact@v4.3.0
        with:
          name: coverage-app
          path: ${{ github.workspace }}/coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
